# Generated by Django 3.0.3 on 2021-03-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('submitter', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('submission_date', models.DateTimeField()),
            ],
        ),
    ]
