# Generated by Django 3.0.3 on 2021-04-08 12:43

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('actual_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='tenant_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_img', models.ImageField(upload_to='images/')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default=True, max_length=22)),
                ('checklist_items', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wet Floors', 'Wet Floors'), ('Oily floors', 'Oily floors'), ('Rats', 'Rats'), ('Safety Hazards', 'Safety Hazards')], default=True, max_length=42, null=True)),
                ('date_audited', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('Staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffscore', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenantchecklistscore', to='accounts.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_audited', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Staff')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tenant')),
            ],
        ),
    ]
