# Generated by Django 3.0.3 on 2021-04-08 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
