# Generated by Django 3.0.3 on 2021-03-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_audit_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Staff'),
        ),
        migrations.AddField(
            model_name='audit',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
