# Generated by Django 3.0.3 on 2021-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenant_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50),
        ),
    ]
