# Generated by Django 3.0.3 on 2021-03-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210319_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='score',
        ),
    ]
