# Generated by Django 3.1.7 on 2021-03-31 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_tenant_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='checklistconditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='null', max_length=20, null=True)),
                ('box', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('score', models.PositiveIntegerField(null=True)),
                ('checked', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('unchecked', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_checklist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fnb', 'fnb'), ('nonfnb', 'nonfnb')], default='no category', max_length=20, null=True)),
                ('items', models.ManyToManyField(related_name='checklist', to='accounts.checklistconditions')),
            ],
        ),
    ]
