# Generated by Django 3.1.7 on 2021-03-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_checklist_checklistconditions_checklistscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='checklistscore',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='checklistscore',
            name='unchecked',
        ),
    ]
