# Generated by Django 3.1.7 on 2021-04-02 07:45

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210331_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistscore',
            name='checked',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='checklistscore',
            name='unchecked',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
    ]
