# Generated by Django 3.1.7 on 2021-04-02 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_auto_20210402_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='staff',
        ),
        migrations.AddField(
            model_name='checklist',
            name='Staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffscore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='score',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ChecklistScore',
        ),
    ]
