# Generated by Django 3.1.7 on 2021-04-02 12:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210402_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='checklist_items',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cockroaches everywhere', 'Cockroaches everywhere'), ('Oily floors', 'Oily floors'), ('Rats', 'Rats'), ('Safety Hazards', 'Safety Hazards')], default=True, max_length=54),
        ),
    ]
