# Generated by Django 3.1.7 on 2021-04-02 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_checklist_checklist_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='score',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
