# Generated by Django 3.1.7 on 2021-04-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210402_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='items',
        ),
        migrations.DeleteModel(
            name='checklistconditions',
        ),
    ]
