# Generated by Django 3.1.7 on 2021-04-04 03:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210402_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='checklist_items',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Wet Floors', 'Wet Floors'), ('Oily floors', 'Oily floors'), ('Rats', 'Rats'), ('Safety Hazards', 'Safety Hazards')], default=True, max_length=42),
        ),
    ]
