# Generated by Django 3.1.7 on 2021-04-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210402_0633'),
        ('accounts', '0019_auto_20210402_1304'),
    ]

    operations = [
    ]
