# Generated by Django 3.1.7 on 2021-04-04 03:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210404_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='checklist_items',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wet Floors', 'Wet Floors'), ('Oily floors', 'Oily floors'), ('Rats', 'Rats'), ('Safety Hazards', 'Safety Hazards')], default=True, max_length=42, null=True),
        ),
    ]
