# Generated by Django 3.1.7 on 2021-04-04 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210404_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='date_audited',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
