# Generated by Django 3.1.7 on 2021-04-04 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_checklist_date_audited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='date_audited',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
