# Generated by Django 3.1.7 on 2021-04-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210404_1219'),
        ('accounts', '0020_merge_20210403_1545'),
    ]

    operations = []
