# Generated by Django 3.1.7 on 2021-04-04 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20210404_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='actual_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
