# Generated by Django 3.1.7 on 2021-04-04 11:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_checklist_actual_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='actual_img',
        ),
        migrations.AddField(
            model_name='image',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='actual_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
