# Generated by Django 3.1.7 on 2021-04-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_checklist_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='comment',
            field=models.TextField(),
        ),
    ]
