# Generated by Django 3.1.7 on 2021-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210405_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
